name       : gitg
version    : 3.23.90
release    : 12
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gitg/3.23/gitg-3.23.90.tar.xz : afb9903e33796ca5149651569280ce15dd53e7d38722146a91db408b9e426f54
license    : GPL-2.0
component  : programming.tools
summary    : gitg is the GNOME GUI client to view git repositories.
description: |
    gitg is the GNOME GUI client to view git repositories.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vapigen)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - gnome-common
    - git
    - gsettings-desktop-schemas-devel
    - intltool
    - vala
setup      : |
    %configure --prefix=/usr --disable-static --disable-maintainer-mode
build      : |
    %make
install    : |
    %make_install
