name       : gitg
version    : 3.20.2
release    : 10
source     :
    - https://download.gnome.org/sources/gitg/3.20/gitg-3.20.2.tar.xz : 76cb421bbc5c1e57d4f58f9e63c7b77ed229cadc96c7de4296db60c46ee7d71b
license    : GPL-2.0
component  : programming.tools
summary    : gitg is the GNOME GUI client to view git repositories.
description: |
    gitg is the GNOME GUI client to view git repositories.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vapigen)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - gnome-common
    - git
    - gsettings-desktop-schemas-devel
    - intltool
    - vala
setup      : |
    %configure --prefix=/usr --disable-static --disable-maintainer-mode
build      : |
    %make
install    : |
    %make_install
